### ISSUE TITLE
Remove UNDO payload requirement in substreams

### ISSUE THREAD

**Issue by sduchesneau** [streamingfast/substreams#199]
The substreams cannot provide payload for "UNDO" material at all times in a pratical manner for multiple reasons:

1) it may contain require "eth_calls" pointing to blocks that were forked out
2) replaying the blocks necessary to bring the "store" in the expected "wrong" state, just to be able to replay the changes, is very complex
3) putting the burden on the substreams developer to gather complete data on a row just to be able to provide "undo data" for a full row is bad. Also, there could be mistakes there, resulting in non-deterministic data because of fork handling.

The solution is to *not* expect the substreams to "try" to provide all undo data, but simply let the engine provide the "undo clock data" (block number and hash), while the sink will hold the necessary logic to handle the UNDO. This could be keeping a keyspace of previous values (in the case of a kv-sink), keeping an encoded value for previous rows or using transaction mechanism in case of an SQL sink, or simply "ignoring undos" in the case of a "slack message notifier".

The burden will go to the sinks based on their requirements. 
As an example, graph-node has its way of handling forks by having time-traversal as a feature of its store, knowing how to "undo" values in its sql rows.

**Comment by jubeless** [comment]
Merging issue: https://github.com/streamingfast/substreams/issues/178 from @abourget 

## Problem

For this block sequence, where chain `b` gets finalized:

```
  9a -> 10a
     `> 10b -> 11b -> 12b
```

An `eth_call` is necessary at block `10a`. It is requested for that specific block ID from the RPC call.  We return the cursor for block `10a` and there is a disconnection.

Upon returning, the block 10a is not there anymore, in any archive node. It has been purged because it has not survived finality.
It is therefore impossible to re-execute `10a`, and re-obtain its payload as it was before.

## Solution

Tweak the response protocol to return only `undo` signals, and not the payload.

## Pushes the problem downstream

The sinks are the ones affected. They now need to keep track of the previous state that is still at risk of being reverted.

For the postgres and kv stores, this was already a problem:
* kv: since a key deletion would not provide the previous value, upon deleting a key, we needed to keep its previous value somewhere until finality.
* postgres: because incoming data is _field_-centric, even with incoming deltas for fields (which makes things much more complex anyway),  we need to keep track of the _other_ fields, when deleting a row. Also, keeping track of previous values in Substreams is extremely error-prone, if not useless when not used by the sink.

Downside: it means that stateless substreams consumers now need to keep state to handle undos, if they care about such things. However, any process that cares about undoing anything needs to track the thing to be undone, and that is already some state. So, I'm left without examples where this is an actual problem.

## Help sinks handle state

 It would be beneficial to have a signal when certain blocks pass finality. This would help the sink purge the state that reaches finality.

**Comment by sduchesneau** [comment]
https://github.com/streamingfast/substreams/pull/204

**Comment by sduchesneau** [comment]
Done
