### ISSUE TITLE
GUI: cycle through different decoding methods for `bytes`

### ISSUE THREAD

**Issue by abourget** [streamingfast/substreams#202]
### Problems

`bytes` are currently displayed as base64-encoded strings, and that's really annoying when what you need is the HEX representation (like addresses, and all).

### Solution

I want to hit `f`, and cycle through the different decoding methods for `bytes`, and just redraw the `outputView` and decode those bytes in `hex`, `unicode strings`, `base64`, .

I'm unsure if that's easily done by the current Go libraries that do the decoding.. but it would be ideal.

**Comment by sduchesneau** [comment]
Problems: this is all done in 'protoreflect/dynamic' which is a huge package, and there is no hook to specify json marshaller on native types like bytes.

either:
1) we change it in there and 'go mod replace' our way to success..
2) we stop using protoreflect which is apparently deprecated https://github.com/jhump/protoreflect#%EF%B8%8F-note and find a way to fix it in the replacement, with `protojson`, etc.
3) we use some kind of postprocessing with gjson/sjson, possibly informed by the protodescs. this solution may incur performance costs.

I have not explored solution 2 enough yet, if it works, I believe it is our best choice..

**Comment by maoueh** [comment]
Other option, we use a standard JSON library that we customize so that we control how bytes are serialized. We could for example "clone" native `encoding/json` library and maintain it but with added capabilities that bytes encoding would be be possible.

I did that in `eth-go` (e.g. copying over `encoding/json` package and modify it to respect JSON-RPC spec, so it's something quite possible).

We could also fork https://github.com/goccy/go-json/blob/master/option.go instead and add option there and upstream the fix, that would reduce long term maintenance burden. However, I prefer personally copying `encoding/json` since it will be "forever" maintained and we benefit from its development. If we do it right, maintaining it with upstream Go release shouldn't be that hard.

Big caveats, maybe this wouldn't work with "dynamic/unknown" type and then my idea make just no sense.

**Comment by sduchesneau** [comment]
After hours spent trying to figure out a way to make it work, 

I did:

This: https://github.com/streamingfast/protoreflect/commit/9691b6ec99b1cea2f0baca63f8adf997751eab30

and called the dynamic.SetDefaultBytesRepresentation() on key 'f', it took only a few minutes.

I will call it a day, then!

created an issue here just in case: https://github.com/jhump/protoreflect/issues/557
but I don't think it will go upstreams on this one or the google protobuf repo, because of this: https://github.com/golang/protobuf/issues/1030

**Comment by sduchesneau** [comment]
Closed with https://github.com/streamingfast/substreams/commit/cf54aae9184e37a443264bbabd8edb5f179e6feb
