### ISSUE TITLE
Substream run not working with "," as a param

### ISSUE THREAD

**Issue by jhjhjh94** [streamingfast/substreams#221]
Running with the command :

>substreams run -e <ip:port> prom_out -s <int> -t +1 -p prom_out="abcdefg,xyz"

Error: param "xyz" invalid, must be of the format: "module=value" or "imported:module=value"

on the other hand 
>substreams gui -e <ip:port> prom_out -s <int> -t +1 -p prom_out="abcdefg,xyz"

 works fine

**Comment by maoueh** [comment]
@emiliocramer Can you take a look

**Comment by jhjhjh94** [comment]
Apologies for any confusion caused by my previous example. Here is a revised version:

substreams **run** -e <ip:port> prom_out -s <block_number> -t +1 -p prom_out="abcdefg,xyz" (doesn't work)

substreams **gui** -e <ip:port> prom_out -s <block_number> -t +1 -p prom_out="abcdefg,xyz" (works)

the difference would be run and gui command.

**Comment by emiliocramer** [comment]
Hey, 
So the issue was just a lack of param handling on the GUI side of things. I've added the proper handling at this commit 1e07b59f8bed536e6c8ec756644448207ef279c5, and now both run and gui should fail with a comma in the param value string, just because the parsing of multiple value flags uses the comma as a delimiter. Example usage: `map_params=abc,map_params2=xyz`

Hope that clears things up
